services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es8
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - data08:/usr/share/elasticsearch/data
    networks:
      - movie-search-network
    mem_limit: 4g
    healthcheck:
      test: curl -s http://es8:9200 >/dev/null || exit 1
      interval: 20s
      timeout: 10s
      retries: 50

  kib8:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200
    ports:
      - 5601:5601
    networks:
      - movie-search-network
    depends_on:
      es8:
        condition: service_healthy

  movie_indexer:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    container_name: indexer
    networks:
      - movie-search-network
    depends_on:
      es8:
        condition: service_healthy

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - movie-search-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: api
    ports:
      - 8080:8080
    networks:
      - movie-search-network
    depends_on:
      redis:
        condition: service_healthy
      es8:
        condition: service_healthy
      movie_indexer:
        condition: service_completed_successfully


volumes:
  data08:
    driver: local

networks:
  movie-search-network:
    driver: bridge


