apiVersion: batch/v1
kind: Job
metadata:
  name: es-initializer
spec:
  template:
    spec:
      containers:
        - name: initializer
          image: thefeij/elasticsearch-initializer:latest
      restartPolicy: Never

